/*
 * Expenses API
 *  The Expenses API allows you to manage accounting and expenses information. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpandableExpenseMerchant
 */
public class ExpandableExpenseMerchantTest {
    private final ExpandableExpenseMerchant model = new ExpandableExpenseMerchant();

    /**
     * Model tests for ExpandableExpenseMerchant
     */
    @Test
    public void testExpandableExpenseMerchant() {
        // TODO: test ExpandableExpenseMerchant
    }

    /**
     * Test the property 'rawDescriptor'
     */
    @Test
    public void rawDescriptorTest() {
        // TODO: test rawDescriptor
    }

    /**
     * Test the property 'mcc'
     */
    @Test
    public void mccTest() {
        // TODO: test mcc
    }

}
