/*
 * Expenses API
 *  The Expenses API allows you to manage accounting and expenses information. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpensePaymentStatus
 */
public class ExpensePaymentStatusTest {
    /**
     * Model tests for ExpensePaymentStatus
     */
    @Test
    public void testExpensePaymentStatus() {
        // TODO: test ExpensePaymentStatus
    }

}
