/*
 * Expenses API
 *  The Expenses API allows you to manage accounting and expenses information. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Category;
import com.konfigthis.client.model.ExpandableExpenseBudget;
import com.konfigthis.client.model.ExpandableExpenseDepartment;
import com.konfigthis.client.model.ExpandableExpenseLocation;
import com.konfigthis.client.model.ExpandableExpenseMerchant;
import com.konfigthis.client.model.ExpandableExpensePayment;
import com.konfigthis.client.model.ExpandableExpenseUser;
import com.konfigthis.client.model.ExpensePaymentStatus;
import com.konfigthis.client.model.ExpenseStatus;
import com.konfigthis.client.model.Money;
import com.konfigthis.client.model.Receipt;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The expense object that has expandable fields, e.g., &#x60;location&#x60;, &#x60;department&#x60;, and &#x60;receipts&#x60;.
 */
@ApiModel(description = "The expense object that has expandable fields, e.g., `location`, `department`, and `receipts`.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ExpandableExpense {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_MEMO = "memo";
  @SerializedName(SERIALIZED_NAME_MEMO)
  private String memo;

  public static final String SERIALIZED_NAME_LOCATION_ID = "location_id";
  @SerializedName(SERIALIZED_NAME_LOCATION_ID)
  private String locationId;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private ExpandableExpenseLocation location;

  public static final String SERIALIZED_NAME_DEPARTMENT_ID = "department_id";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT_ID)
  private String departmentId;

  public static final String SERIALIZED_NAME_DEPARTMENT = "department";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT)
  private ExpandableExpenseDepartment department;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private Category category;

  public static final String SERIALIZED_NAME_MERCHANT_ID = "merchant_id";
  @SerializedName(SERIALIZED_NAME_MERCHANT_ID)
  private String merchantId;

  public static final String SERIALIZED_NAME_MERCHANT = "merchant";
  @SerializedName(SERIALIZED_NAME_MERCHANT)
  private ExpandableExpenseMerchant merchant;

  public static final String SERIALIZED_NAME_RECEIPTS = "receipts";
  @SerializedName(SERIALIZED_NAME_RECEIPTS)
  private List<Receipt> receipts = null;

  public static final String SERIALIZED_NAME_BUDGET_ID = "budget_id";
  @SerializedName(SERIALIZED_NAME_BUDGET_ID)
  private String budgetId;

  public static final String SERIALIZED_NAME_BUDGET = "budget";
  @SerializedName(SERIALIZED_NAME_BUDGET)
  private ExpandableExpenseBudget budget;

  public static final String SERIALIZED_NAME_ORIGINAL_AMOUNT = "original_amount";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_AMOUNT)
  private Money originalAmount;

  public static final String SERIALIZED_NAME_PURCHASED_AT = "purchased_at";
  @SerializedName(SERIALIZED_NAME_PURCHASED_AT)
  private OffsetDateTime purchasedAt;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private ExpenseStatus status;

  public static final String SERIALIZED_NAME_PAYMENT_STATUS = "payment_status";
  @SerializedName(SERIALIZED_NAME_PAYMENT_STATUS)
  private ExpensePaymentStatus paymentStatus;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private ExpandableExpenseUser user;

  public static final String SERIALIZED_NAME_PAYMENT = "payment";
  @SerializedName(SERIALIZED_NAME_PAYMENT)
  private ExpandableExpensePayment payment;

  public ExpandableExpense() {
  }

  public ExpandableExpense id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Unique ID associated with the expense.
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Unique ID associated with the expense.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public ExpandableExpense memo(String memo) {
    
    
    
    
    this.memo = memo;
    return this;
  }

   /**
   * The memo of the expense.
   * @return memo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The memo of the expense.")

  public String getMemo() {
    return memo;
  }


  public void setMemo(String memo) {
    
    
    
    this.memo = memo;
  }


  public ExpandableExpense locationId(String locationId) {
    
    
    
    
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLocationId() {
    return locationId;
  }


  public void setLocationId(String locationId) {
    
    
    
    this.locationId = locationId;
  }


  public ExpandableExpense location(ExpandableExpenseLocation location) {
    
    
    
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpandableExpenseLocation getLocation() {
    return location;
  }


  public void setLocation(ExpandableExpenseLocation location) {
    
    
    
    this.location = location;
  }


  public ExpandableExpense departmentId(String departmentId) {
    
    
    
    
    this.departmentId = departmentId;
    return this;
  }

   /**
   * Get departmentId
   * @return departmentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDepartmentId() {
    return departmentId;
  }


  public void setDepartmentId(String departmentId) {
    
    
    
    this.departmentId = departmentId;
  }


  public ExpandableExpense department(ExpandableExpenseDepartment department) {
    
    
    
    
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpandableExpenseDepartment getDepartment() {
    return department;
  }


  public void setDepartment(ExpandableExpenseDepartment department) {
    
    
    
    this.department = department;
  }


  public ExpandableExpense updatedAt(OffsetDateTime updatedAt) {
    
    
    
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The last time the expense was updated.
   * @return updatedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The last time the expense was updated.")

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    
    
    
    this.updatedAt = updatedAt;
  }


  public ExpandableExpense category(Category category) {
    
    
    
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Category getCategory() {
    return category;
  }


  public void setCategory(Category category) {
    
    
    
    this.category = category;
  }


  public ExpandableExpense merchantId(String merchantId) {
    
    
    
    
    this.merchantId = merchantId;
    return this;
  }

   /**
   * Get merchantId
   * @return merchantId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMerchantId() {
    return merchantId;
  }


  public void setMerchantId(String merchantId) {
    
    
    
    this.merchantId = merchantId;
  }


  public ExpandableExpense merchant(ExpandableExpenseMerchant merchant) {
    
    
    
    
    this.merchant = merchant;
    return this;
  }

   /**
   * Get merchant
   * @return merchant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpandableExpenseMerchant getMerchant() {
    return merchant;
  }


  public void setMerchant(ExpandableExpenseMerchant merchant) {
    
    
    
    this.merchant = merchant;
  }


  public ExpandableExpense receipts(List<Receipt> receipts) {
    
    
    
    
    this.receipts = receipts;
    return this;
  }

  public ExpandableExpense addReceiptsItem(Receipt receiptsItem) {
    if (this.receipts == null) {
      this.receipts = new ArrayList<>();
    }
    this.receipts.add(receiptsItem);
    return this;
  }

   /**
   * A list of receipts associated with the expense.
   * @return receipts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of receipts associated with the expense.")

  public List<Receipt> getReceipts() {
    return receipts;
  }


  public void setReceipts(List<Receipt> receipts) {
    
    
    
    this.receipts = receipts;
  }


  public ExpandableExpense budgetId(String budgetId) {
    
    
    
    
    this.budgetId = budgetId;
    return this;
  }

   /**
   * Get budgetId
   * @return budgetId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBudgetId() {
    return budgetId;
  }


  public void setBudgetId(String budgetId) {
    
    
    
    this.budgetId = budgetId;
  }


  public ExpandableExpense budget(ExpandableExpenseBudget budget) {
    
    
    
    
    this.budget = budget;
    return this;
  }

   /**
   * Get budget
   * @return budget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpandableExpenseBudget getBudget() {
    return budget;
  }


  public void setBudget(ExpandableExpenseBudget budget) {
    
    
    
    this.budget = budget;
  }


  public ExpandableExpense originalAmount(Money originalAmount) {
    
    
    
    
    this.originalAmount = originalAmount;
    return this;
  }

   /**
   * Get originalAmount
   * @return originalAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Money getOriginalAmount() {
    return originalAmount;
  }


  public void setOriginalAmount(Money originalAmount) {
    
    
    
    this.originalAmount = originalAmount;
  }


  public ExpandableExpense purchasedAt(OffsetDateTime purchasedAt) {
    
    
    
    
    this.purchasedAt = purchasedAt;
    return this;
  }

   /**
   * The time the purchase was made.
   * @return purchasedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time the purchase was made.")

  public OffsetDateTime getPurchasedAt() {
    return purchasedAt;
  }


  public void setPurchasedAt(OffsetDateTime purchasedAt) {
    
    
    
    this.purchasedAt = purchasedAt;
  }


  public ExpandableExpense status(ExpenseStatus status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpenseStatus getStatus() {
    return status;
  }


  public void setStatus(ExpenseStatus status) {
    
    
    
    this.status = status;
  }


  public ExpandableExpense paymentStatus(ExpensePaymentStatus paymentStatus) {
    
    
    
    
    this.paymentStatus = paymentStatus;
    return this;
  }

   /**
   * Get paymentStatus
   * @return paymentStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpensePaymentStatus getPaymentStatus() {
    return paymentStatus;
  }


  public void setPaymentStatus(ExpensePaymentStatus paymentStatus) {
    
    
    
    this.paymentStatus = paymentStatus;
  }


  public ExpandableExpense userId(String userId) {
    
    
    
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    
    
    
    this.userId = userId;
  }


  public ExpandableExpense user(ExpandableExpenseUser user) {
    
    
    
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpandableExpenseUser getUser() {
    return user;
  }


  public void setUser(ExpandableExpenseUser user) {
    
    
    
    this.user = user;
  }


  public ExpandableExpense payment(ExpandableExpensePayment payment) {
    
    
    
    
    this.payment = payment;
    return this;
  }

   /**
   * Get payment
   * @return payment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ExpandableExpensePayment getPayment() {
    return payment;
  }


  public void setPayment(ExpandableExpensePayment payment) {
    
    
    
    this.payment = payment;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExpandableExpense instance itself
   */
  public ExpandableExpense putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpandableExpense expandableExpense = (ExpandableExpense) o;
    return Objects.equals(this.id, expandableExpense.id) &&
        Objects.equals(this.memo, expandableExpense.memo) &&
        Objects.equals(this.locationId, expandableExpense.locationId) &&
        Objects.equals(this.location, expandableExpense.location) &&
        Objects.equals(this.departmentId, expandableExpense.departmentId) &&
        Objects.equals(this.department, expandableExpense.department) &&
        Objects.equals(this.updatedAt, expandableExpense.updatedAt) &&
        Objects.equals(this.category, expandableExpense.category) &&
        Objects.equals(this.merchantId, expandableExpense.merchantId) &&
        Objects.equals(this.merchant, expandableExpense.merchant) &&
        Objects.equals(this.receipts, expandableExpense.receipts) &&
        Objects.equals(this.budgetId, expandableExpense.budgetId) &&
        Objects.equals(this.budget, expandableExpense.budget) &&
        Objects.equals(this.originalAmount, expandableExpense.originalAmount) &&
        Objects.equals(this.purchasedAt, expandableExpense.purchasedAt) &&
        Objects.equals(this.status, expandableExpense.status) &&
        Objects.equals(this.paymentStatus, expandableExpense.paymentStatus) &&
        Objects.equals(this.userId, expandableExpense.userId) &&
        Objects.equals(this.user, expandableExpense.user) &&
        Objects.equals(this.payment, expandableExpense.payment)&&
        Objects.equals(this.additionalProperties, expandableExpense.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, memo, locationId, location, departmentId, department, updatedAt, category, merchantId, merchant, receipts, budgetId, budget, originalAmount, purchasedAt, status, paymentStatus, userId, user, payment, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpandableExpense {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    merchant: ").append(toIndentedString(merchant)).append("\n");
    sb.append("    receipts: ").append(toIndentedString(receipts)).append("\n");
    sb.append("    budgetId: ").append(toIndentedString(budgetId)).append("\n");
    sb.append("    budget: ").append(toIndentedString(budget)).append("\n");
    sb.append("    originalAmount: ").append(toIndentedString(originalAmount)).append("\n");
    sb.append("    purchasedAt: ").append(toIndentedString(purchasedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    paymentStatus: ").append(toIndentedString(paymentStatus)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("memo");
    openapiFields.add("location_id");
    openapiFields.add("location");
    openapiFields.add("department_id");
    openapiFields.add("department");
    openapiFields.add("updated_at");
    openapiFields.add("category");
    openapiFields.add("merchant_id");
    openapiFields.add("merchant");
    openapiFields.add("receipts");
    openapiFields.add("budget_id");
    openapiFields.add("budget");
    openapiFields.add("original_amount");
    openapiFields.add("purchased_at");
    openapiFields.add("status");
    openapiFields.add("payment_status");
    openapiFields.add("user_id");
    openapiFields.add("user");
    openapiFields.add("payment");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("updated_at");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ExpandableExpense
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ExpandableExpense.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpandableExpense is not found in the empty JSON string", ExpandableExpense.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ExpandableExpense.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("memo").isJsonNull() && (jsonObj.get("memo") != null && !jsonObj.get("memo").isJsonNull()) && !jsonObj.get("memo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `memo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("memo").toString()));
      }
      if (!jsonObj.get("location_id").isJsonNull() && (jsonObj.get("location_id") != null && !jsonObj.get("location_id").isJsonNull()) && !jsonObj.get("location_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `location_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("location_id").toString()));
      }
      // validate the optional field `location`
      if (jsonObj.get("location") != null && !jsonObj.get("location").isJsonNull()) {
        ExpandableExpenseLocation.validateJsonObject(jsonObj.getAsJsonObject("location"));
      }
      if (!jsonObj.get("department_id").isJsonNull() && (jsonObj.get("department_id") != null && !jsonObj.get("department_id").isJsonNull()) && !jsonObj.get("department_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `department_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("department_id").toString()));
      }
      // validate the optional field `department`
      if (jsonObj.get("department") != null && !jsonObj.get("department").isJsonNull()) {
        ExpandableExpenseDepartment.validateJsonObject(jsonObj.getAsJsonObject("department"));
      }
      // validate the optional field `category`
      if (jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) {
        Category.validateJsonObject(jsonObj.getAsJsonObject("category"));
      }
      if (!jsonObj.get("merchant_id").isJsonNull() && (jsonObj.get("merchant_id") != null && !jsonObj.get("merchant_id").isJsonNull()) && !jsonObj.get("merchant_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchant_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchant_id").toString()));
      }
      // validate the optional field `merchant`
      if (jsonObj.get("merchant") != null && !jsonObj.get("merchant").isJsonNull()) {
        ExpandableExpenseMerchant.validateJsonObject(jsonObj.getAsJsonObject("merchant"));
      }
      if (jsonObj.get("receipts") != null && !jsonObj.get("receipts").isJsonNull()) {
        JsonArray jsonArrayreceipts = jsonObj.getAsJsonArray("receipts");
        if (jsonArrayreceipts != null) {
          // ensure the json data is an array
          if (!jsonObj.get("receipts").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `receipts` to be an array in the JSON string but got `%s`", jsonObj.get("receipts").toString()));
          }

          // validate the optional field `receipts` (array)
          for (int i = 0; i < jsonArrayreceipts.size(); i++) {
            Receipt.validateJsonObject(jsonArrayreceipts.get(i).getAsJsonObject());
          };
        }
      }
      if (!jsonObj.get("budget_id").isJsonNull() && (jsonObj.get("budget_id") != null && !jsonObj.get("budget_id").isJsonNull()) && !jsonObj.get("budget_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `budget_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("budget_id").toString()));
      }
      // validate the optional field `budget`
      if (jsonObj.get("budget") != null && !jsonObj.get("budget").isJsonNull()) {
        ExpandableExpenseBudget.validateJsonObject(jsonObj.getAsJsonObject("budget"));
      }
      // validate the optional field `original_amount`
      if (jsonObj.get("original_amount") != null && !jsonObj.get("original_amount").isJsonNull()) {
        Money.validateJsonObject(jsonObj.getAsJsonObject("original_amount"));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        ExpenseStatus.validateJsonObject(jsonObj.getAsJsonObject("status"));
      }
      // validate the optional field `payment_status`
      if (jsonObj.get("payment_status") != null && !jsonObj.get("payment_status").isJsonNull()) {
        ExpensePaymentStatus.validateJsonObject(jsonObj.getAsJsonObject("payment_status"));
      }
      if (!jsonObj.get("user_id").isJsonNull() && (jsonObj.get("user_id") != null && !jsonObj.get("user_id").isJsonNull()) && !jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_id").toString()));
      }
      // validate the optional field `user`
      if (jsonObj.get("user") != null && !jsonObj.get("user").isJsonNull()) {
        ExpandableExpenseUser.validateJsonObject(jsonObj.getAsJsonObject("user"));
      }
      // validate the optional field `payment`
      if (jsonObj.get("payment") != null && !jsonObj.get("payment").isJsonNull()) {
        ExpandableExpensePayment.validateJsonObject(jsonObj.getAsJsonObject("payment"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpandableExpense.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpandableExpense' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpandableExpense> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpandableExpense.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpandableExpense>() {
           @Override
           public void write(JsonWriter out, ExpandableExpense value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpandableExpense read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ExpandableExpense instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpandableExpense given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpandableExpense
  * @throws IOException if the JSON string is invalid with respect to ExpandableExpense
  */
  public static ExpandableExpense fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpandableExpense.class);
  }

 /**
  * Convert an instance of ExpandableExpense to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

