/*
 * Expenses API
 *  The Expenses API allows you to manage accounting and expenses information. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ExpenseStatus
 */
@JsonAdapter(ExpenseStatus.Adapter.class)public enum ExpenseStatus {
  
  DRAFT("DRAFT"),
  
  SUBMITTED("SUBMITTED"),
  
  APPROVED("APPROVED"),
  
  OUT_OF_POLICY("OUT_OF_POLICY"),
  
  VOID("VOID"),
  
  CANCELED("CANCELED"),
  
  SPLIT("SPLIT"),
  
  SETTLED("SETTLED");

  private String value;

  ExpenseStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ExpenseStatus fromValue(String value) {
    for (ExpenseStatus b : ExpenseStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ExpenseStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final ExpenseStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ExpenseStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ExpenseStatus.fromValue(value);
    }
  }
}

