/*
 * Expenses API
 *  The Expenses API allows you to manage accounting and expenses information. 
 *
 * The version of the OpenAPI document: 0.1
 * Contact: developer-access@brex.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CreateAsyncFileUploadResponse;
import com.konfigthis.client.model.ReceiptUploadRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReceiptUploadApi
 */
@Disabled
public class ReceiptUploadApiTest {

    private static ReceiptUploadApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ReceiptUploadApi(apiClient);
    }

    /**
     * Create a new receipt upload
     *
     *  The &#x60;uri&#x60; will be a pre-signed S3 URL allowing you to upload the receipt securely. This URL can only be used for a &#x60;PUT&#x60; operation and expires 30 minutes after its creation. Once your upload is complete, we will try to match the receipt with existing expenses.  Refer to these [docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html) on how to upload to this pre-signed S3 URL. We highly recommend using one of AWS SDKs if they&#39;re available for your language to upload these files. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewReceiptTest() throws ApiException {
        String receiptName = null;
        String expenseId = null;
        CreateAsyncFileUploadResponse response = api.createNewReceipt(receiptName, expenseId)
                .execute();
        // TODO: test validations
    }

}
